2019/10/29 13:48:10 [error] 7#7: *1 FastCGI sent in stderr: "Primary script unknown" while reading response header from upstream, client: 192.168.9.1, server: symfony.localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.3:9001", host: "symfony.localhost"
2019/10/29 13:48:13 [error] 7#7: *4 FastCGI sent in stderr: "Primary script unknown" while reading response header from upstream, client: 192.168.9.1, server: symfony.localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.3:9001", host: "symfony.localhost"
2019/10/29 13:48:13 [error] 7#7: *4 FastCGI sent in stderr: "Primary script unknown" while reading response header from upstream, client: 192.168.9.1, server: symfony.localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.19.0.3:9001", host: "symfony.localhost"
2019/10/29 13:48:14 [error] 7#7: *4 FastCGI sent in stderr: "Primary script unknown" while reading response header from upstream, client: 192.168.9.1, server: symfony.localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.3:9001", host: "symfony.localhost"
2019/10/29 13:48:14 [error] 7#7: *4 FastCGI sent in stderr: "Primary script unknown" while reading response header from upstream, client: 192.168.9.1, server: symfony.localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.3:9001", host: "symfony.localhost"
2019/10/29 13:48:14 [error] 7#7: *4 FastCGI sent in stderr: "Primary script unknown" while reading response header from upstream, client: 192.168.9.1, server: symfony.localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.3:9001", host: "symfony.localhost"
2019/10/29 13:48:15 [error] 7#7: *4 FastCGI sent in stderr: "Primary script unknown" while reading response header from upstream, client: 192.168.9.1, server: symfony.localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.3:9001", host: "symfony.localhost"
2019/10/29 13:57:57 [error] 6#6: *1 FastCGI sent in stderr: "Primary script unknown" while reading response header from upstream, client: 192.168.9.1, server: symfony.localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.3:9001", host: "symfony.localhost"
2019/10/29 13:57:57 [error] 6#6: *1 FastCGI sent in stderr: "Primary script unknown" while reading response header from upstream, client: 192.168.9.1, server: symfony.localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.3:9001", host: "symfony.localhost"
2019/10/29 13:57:58 [error] 6#6: *1 FastCGI sent in stderr: "Primary script unknown" while reading response header from upstream, client: 192.168.9.1, server: symfony.localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.3:9001", host: "symfony.localhost"
2019/10/30 04:45:36 [error] 9#9: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.9.1, server: symfony.localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.18.0.3:9001", host: "symfony.localhost"
2019/10/30 04:45:40 [error] 9#9: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.9.1, server: symfony.localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.18.0.3:9001", host: "symfony.localhost"
2019/10/30 04:45:41 [error] 9#9: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.9.1, server: symfony.localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.18.0.3:9001", host: "symfony.localhost"
2019/10/30 04:45:42 [error] 9#9: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.9.1, server: symfony.localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.18.0.3:9001", host: "symfony.localhost"
2019/10/30 04:45:42 [error] 9#9: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.9.1, server: symfony.localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.18.0.3:9001", host: "symfony.localhost"
2019/10/30 04:45:49 [error] 9#9: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.9.1, server: symfony.localhost, request: "GET /v1/testDatabase HTTP/1.1", upstream: "fastcgi://172.18.0.3:9001", host: "symfony.localhost"
2019/10/30 04:45:51 [error] 9#9: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.9.1, server: symfony.localhost, request: "GET /v1/testDatabase HTTP/1.1", upstream: "fastcgi://172.18.0.3:9001", host: "symfony.localhost"
2019/10/30 04:53:35 [error] 7#7: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.9.41, server: symfony.localhost, request: "GET /v1/testDatabase HTTP/1.1", upstream: "fastcgi://172.19.0.3:9001", host: "symfony.localhost"
